import type {
  TabletBaseDefinition,
  TabletModDefinition,
} from "./tablet-types";

/**
 * Approximate tablet affix pools & weights for EV simulation.
 *
 * PoE2DB: "Modifier weight information cannot be obtained from game files."
 * Patch 0.3.1 added filler mods that flood the explicit pool (Mobalytics /
 * community notes). Weights below are seed estimates: desirable mods stay
 * scarce (~250–600), shared junk fillers dominate (~1100–1500) so hit rates
 * under-estimate rather than over-estimate.
 *
 * Rares are modeled as 2 prefixes + 2 suffixes (see tablet-mdp).
 */

/** Shared map-content junk (0.3.1 fillers + common generic) — all tablet bases. */
export const SHARED_GENERIC_PREFIXES = [
  "junk_item_rarity_t1",
  "junk_gold_t1",
  "junk_xp_t1",
  "junk_magic_mons_t1",
  "junk_rare_mons_t1",
  "junk_rare_chests_t1",
  "junk_monster_eff_t1",
  "junk_extra_essence_t1",
  "junk_extra_exile_t1",
  "junk_extra_azmeri_t1",
  "junk_extra_summon_t1",
] as const;

export const SHARED_GENERIC_SUFFIXES = [
  "junk_extra_shrine_t1",
  "junk_extra_strongbox_t1",
  "junk_shrine_chance_t1",
  "junk_strongbox_chance_t1",
  "junk_essence_chance_t1",
  "junk_exile_chance_t1",
  "junk_summon_chance_t1",
  "junk_azmeri_chance_t1",
  "junk_map_mods_t1",
  "junk_rare_extra_mod_t1",
] as const;

function uniqIds(...groups: readonly (readonly string[])[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const g of groups) {
    for (const id of g) {
      if (seen.has(id)) continue;
      seen.add(id);
      out.push(id);
    }
  }
  return out;
}

function pools(
  prefixes: readonly string[],
  suffixes: readonly string[],
): Pick<TabletBaseDefinition, "allowedPrefixPool" | "allowedSuffixPool"> {
  return {
    allowedPrefixPool: uniqIds(prefixes, SHARED_GENERIC_PREFIXES),
    allowedSuffixPool: uniqIds(suffixes, SHARED_GENERIC_SUFFIXES),
  };
}

export const TABLET_BASES: Record<string, TabletBaseDefinition> = {
  breach_tablet: {
    id: "breach_tablet",
    name: "Breach Tablet",
    aliases: ["Breach Precursor Tablet", "Precursor Tablet of the Breach"],
    category: "Breach",
    tag: "tower_augment_breach",
    ...pools(
      [
        "breach_pack_size_t1",
        "breach_pack_size_t2",
        "breach_rare_potency_t1",
        "map_quantity_t2",
        "map_pack_size_t2",
      ],
      [
        "breach_splinter_qty_t1",
        "breach_splinter_qty_t2",
        "breach_hiveblood_t1",
        "breach_wombgift_qty_t1",
        "breach_unstable_rare_t1",
        "breach_vruun_chance_t1",
      ],
    ),
    maxAffixes: 4,
  },
  delirium_tablet: {
    id: "delirium_tablet",
    name: "Delirium Tablet",
    aliases: ["Delirium Precursor Tablet", "Precursor Tablet of Delirium"],
    category: "Delirium",
    tag: "tower_augment_delirium",
    ...pools(
      [
        "delirium_pack_size_t1",
        "delirium_pack_size_t2",
        "map_pack_size_t1",
        "map_pack_size_t2",
        "map_quantity_t2",
      ],
      [
        "delirium_splinter_stack_t1",
        "delirium_splinter_stack_t2",
        "delirium_boss_chance_t1",
        "delirium_fog_duration_t1",
        "delirium_mirror_shards_t1",
        "delirium_timer_pause_t1",
      ],
    ),
    maxAffixes: 4,
  },
  expedition_tablet: {
    id: "expedition_tablet",
    name: "Expedition Tablet",
    aliases: [
      "Expedition Precursor Tablet",
      "Precursor Tablet of the Expedition",
    ],
    category: "Expedition",
    tag: "tower_augment_expedition",
    ...pools(
      [
        "expedition_relic_effect_t1",
        "expedition_rare_monsters_t1",
        "map_pack_size_t2",
        "map_quantity_t2",
        "expedition_markers_t1",
      ],
      [
        "expedition_logbook_t1",
        "expedition_logbook_t2",
        "expedition_artifacts_t1",
        "expedition_explosive_radius_t1",
        "expedition_remnants_t1",
      ],
    ),
    maxAffixes: 4,
  },
  ritual_tablet: {
    id: "ritual_tablet",
    name: "Ritual Tablet",
    aliases: ["Ritual Precursor Tablet", "Precursor Tablet of Ritual"],
    category: "Ritual",
    tag: "tower_augment_ritual",
    ...pools(
      ["map_pack_size_t1", "map_pack_size_t2", "map_quantity_t2"],
      [
        "map_rarity_t1",
        "map_quantity_t1",
        "ritual_tribute_t1",
        "ritual_reroll_t1",
        "ritual_omen_t1",
        "ritual_defer_t1",
      ],
    ),
    maxAffixes: 4,
  },
  overseer_tablet: {
    id: "overseer_tablet",
    name: "Overseer Tablet",
    aliases: [
      "Overseer Precursor Tablet",
      "Boss Precursor Tablet",
      "Precursor Tablet of the Boss",
    ],
    category: "Boss",
    tag: "tower_augment_map_boss",
    ...pools(
      ["boss_item_rarity_t1", "map_quantity_t1", "map_pack_size_t2", "map_quantity_t2"],
      [
        "boss_waystone_qty_t1",
        "boss_waystone_qty_t2",
        "map_rarity_t1",
        "boss_xp_t1",
        "boss_item_qty_t1",
      ],
    ),
    maxAffixes: 4,
  },
  abyss_tablet: {
    id: "abyss_tablet",
    name: "Abyss Tablet",
    aliases: ["Abyss Precursor Tablet"],
    category: "Abyss",
    tag: "tower_augment_abyss",
    ...pools(
      [
        "abyss_monster_spawn_t1",
        "abyss_monster_spawn_t2",
        "map_pack_size_t2",
        "map_quantity_t2",
      ],
      [
        "abyss_desecrated_t1",
        "abyss_depths_t1",
        "abyss_extra_t1",
        "abyss_pit_reward_t1",
        "abyss_rare_spawn_t1",
      ],
    ),
    maxAffixes: 4,
  },
  irradiated_tablet: {
    id: "irradiated_tablet",
    name: "Irradiated Tablet",
    aliases: [
      "Irradiated Precursor Tablet",
      "Generic Precursor Tablet",
      "Precursor Tablet",
    ],
    category: "Irradiated",
    tag: "tower_augment_generic",
    ...pools(
      ["map_pack_size_t1", "map_pack_size_t2", "map_quantity_t2"],
      ["map_rarity_t1", "map_quantity_t1", "map_waystone_qty_t1"],
    ),
    maxAffixes: 4,
  },
  temple_tablet: {
    id: "temple_tablet",
    name: "Temple Tablet",
    aliases: ["Temple Precursor Tablet", "Incursion Precursor Tablet"],
    category: "Temple",
    tag: "tower_augment_incursion",
    ...pools(
      ["map_pack_size_t2", "map_quantity_t2"],
      [
        "map_rarity_t1",
        "map_quantity_t1",
        "temple_beacon_pack_t1",
        "temple_crystal_t1",
        "temple_chest_rare_t1",
      ],
    ),
    maxAffixes: 4,
  },
};

export const TABLET_MOD_WEIGHTS: Record<string, TabletModDefinition> = {
  // Shared / irradiated
  map_pack_size_t1: {
    id: "map_pack_size_t1",
    name: "#% increased Pack Size in Map",
    statPattern: /(\d+)% increased Pack Size in Map/i,
    statRef: "#% increased Pack Size in Map",
    tradeStatId: "explicit.stat_2017682521",
    tier: 1,
    weight: 400,
    minValue: 8,
    maxValue: 12,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 85,
    regexHint: "pa",
  },
  map_pack_size_t2: {
    id: "map_pack_size_t2",
    name: "#% increased Pack Size in Map",
    statPattern: /(\d+)% increased Pack Size in Map/i,
    statRef: "#% increased Pack Size in Map",
    tradeStatId: "explicit.stat_2017682521",
    tier: 2,
    weight: 800,
    minValue: 4,
    maxValue: 7,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 55,
    regexHint: "pa",
  },
  map_quantity_t1: {
    id: "map_quantity_t1",
    name: "#% increased Quantity of Items found in Map",
    statPattern: /(\d+)% increased Quantity of Items found in Map/i,
    statRef: "#% increased Quantity of Items found in Map",
    tradeStatId: "explicit.stat_2390685262",
    tier: 1,
    weight: 500,
    minValue: 10,
    maxValue: 20,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 70,
    regexHint: "quan",
  },
  map_quantity_t2: {
    id: "map_quantity_t2",
    name: "#% increased Quantity of Items found in Map",
    statPattern: /(\d+)% increased Quantity of Items found in Map/i,
    statRef: "#% increased Quantity of Items found in Map",
    tradeStatId: "explicit.stat_2390685262",
    tier: 2,
    weight: 900,
    minValue: 5,
    maxValue: 9,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 40,
    regexHint: "quan",
  },
  map_rarity_t1: {
    id: "map_rarity_t1",
    name: "#% increased Rarity of Items found in Map",
    statPattern: /(\d+)% increased Rarity of Items found in Map/i,
    tradeStatId: "explicit.stat_4011150624",
    tier: 1,
    weight: 600,
    minValue: 10,
    maxValue: 25,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 50,
    regexHint: "rar",
  },
  map_waystone_qty_t1: {
    id: "map_waystone_qty_t1",
    name: "#% increased Quantity of Waystones found in Map",
    statPattern: /(\d+)% increased Quantity of Waystones found in Map/i,
    tradeStatId: "explicit.stat_2777224821",
    tier: 1,
    weight: 450,
    minValue: 10,
    maxValue: 25,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 65,
    regexHint: "ways",
  },

  // Breach
  breach_pack_size_t1: {
    id: "breach_pack_size_t1",
    name: "#% increased Pack Size in Map",
    statPattern: /(\d+)% increased Pack Size in Map/i,
    statRef: "#% increased Pack Size in Map",
    tradeStatId: "explicit.stat_2017682521",
    tier: 1,
    weight: 350,
    // "Breeding" is 6–10%
    minValue: 8,
    maxValue: 10,
    isPrefix: true,
    category: "Breach",
    valueScore: 90,
    regexHint: "pa",
  },
  breach_pack_size_t2: {
    id: "breach_pack_size_t2",
    name: "#% increased Pack Size in Map",
    statPattern: /(\d+)% increased Pack Size in Map/i,
    tradeStatId: "explicit.stat_2017682521",
    tier: 2,
    weight: 700,
    minValue: 6,
    maxValue: 7,
    isPrefix: true,
    category: "Breach",
    valueScore: 50,
    regexHint: "pa",
  },
  breach_rare_potency_t1: {
    id: "breach_rare_potency_t1",
    name: "#% increased Effectiveness of Rare Breach Monsters in Map",
    statPattern:
      /(\d+)% increased Effectiveness of Rare Breach Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_2895378479",
    tier: 1,
    weight: 400,
    minValue: 15,
    maxValue: 30,
    isPrefix: true,
    category: "Breach",
    valueScore: 75,
    regexHint: "eff.*bre|bre.*eff",
  },
  breach_splinter_qty_t1: {
    id: "breach_splinter_qty_t1",
    name: "#% increased Quantity of Breach Splinters dropped by Breach Monsters in Map",
    statPattern:
      /(\d+)% increased Quantity of Breach Splinters dropped by Breach Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_624534143",
    tier: 1,
    weight: 300,
    // "of the Domain" is 15–30% (patch); upper half
    minValue: 23,
    maxValue: 30,
    isPrefix: false,
    category: "Breach",
    valueScore: 95,
    regexHint: "spl",
  },
  breach_splinter_qty_t2: {
    id: "breach_splinter_qty_t2",
    name: "#% increased Quantity of Breach Splinters dropped by Breach Monsters in Map",
    statPattern:
      /(\d+)% increased Quantity of Breach Splinters dropped by Breach Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_624534143",
    tier: 2,
    weight: 650,
    // Domain floor is 15% — old 10–19 split was stale
    minValue: 15,
    maxValue: 22,
    isPrefix: false,
    category: "Breach",
    valueScore: 60,
    regexHint: "spl",
  },
  breach_hiveblood_t1: {
    id: "breach_hiveblood_t1",
    name: "#% increased Quantity of Hiveblood found in Map",
    statPattern: /(\d+)% increased Quantity of Hiveblood found(?: in Map)?/i,
    tradeStatId: "explicit.stat_2778285247",
    tier: 1,
    weight: 500,
    minValue: 10,
    maxValue: 25,
    isPrefix: false,
    category: "Breach",
    valueScore: 55,
    regexHint: "hive",
  },

  // Delirium
  delirium_pack_size_t1: {
    id: "delirium_pack_size_t1",
    name: "Delirium Monsters in Map have #% increased Pack Size",
    statPattern:
      /Delirium Monsters in Map have (\d+)% increased Pack Size/i,
    tradeStatId: "explicit.stat_3465791711",
    tier: 1,
    weight: 350,
    minValue: 10,
    maxValue: 20,
    isPrefix: true,
    category: "Delirium",
    valueScore: 88,
    regexHint: "del.*pa|pa.*del",
  },
  delirium_pack_size_t2: {
    id: "delirium_pack_size_t2",
    name: "Delirium Monsters in Map have #% increased Pack Size",
    statPattern:
      /Delirium Monsters in Map have (\d+)% increased Pack Size/i,
    tradeStatId: "explicit.stat_3465791711",
    tier: 2,
    weight: 700,
    minValue: 5,
    maxValue: 9,
    isPrefix: true,
    category: "Delirium",
    valueScore: 45,
    regexHint: "del.*pa|pa.*del",
  },
  delirium_splinter_stack_t1: {
    id: "delirium_splinter_stack_t1",
    name: "#% increased Stack size of Simulacrum Splinters found in Map",
    statPattern:
      /(\d+)% increased Stack size of Simulacrum Splinters found(?: in Map)?/i,
    tradeStatId: "explicit.stat_3836551197",
    tier: 1,
    weight: 280,
    minValue: 15,
    maxValue: 30,
    isPrefix: false,
    category: "Delirium",
    valueScore: 98,
    regexHint: "simu|stack.*spl",
  },
  delirium_splinter_stack_t2: {
    id: "delirium_splinter_stack_t2",
    name: "#% increased Stack size of Simulacrum Splinters found in Map",
    statPattern:
      /(\d+)% increased Stack size of Simulacrum Splinters found(?: in Map)?/i,
    tradeStatId: "explicit.stat_3836551197",
    tier: 2,
    weight: 600,
    minValue: 8,
    maxValue: 14,
    isPrefix: false,
    category: "Delirium",
    valueScore: 55,
    regexHint: "simu",
  },
  delirium_boss_chance_t1: {
    id: "delirium_boss_chance_t1",
    name: "Delirium Encounters in Map are #% more likely to spawn Unique Bosses",
    statPattern:
      /Delirium Encounters in Map are (\d+)% more likely to spawn Unique Bosses/i,
    tradeStatId: "explicit.stat_3962960008",
    tier: 1,
    weight: 400,
    minValue: 10,
    maxValue: 30,
    isPrefix: false,
    category: "Delirium",
    valueScore: 80,
    regexHint: "boss",
  },

  // Expedition
  expedition_relic_effect_t1: {
    id: "expedition_relic_effect_t1",
    name: "#% increased Effect of Expedition Remnants in Map",
    statPattern:
      /(\d+)% increased Effect of (?:Expedition )?Remnants(?: in Map| in Area| in your Maps)?/i,
    tradeStatId: "explicit.stat_3078574625",
    tier: 1,
    weight: 450,
    minValue: 15,
    maxValue: 30,
    isPrefix: true,
    category: "Expedition",
    valueScore: 72,
    regexHint: "remn",
  },
  expedition_rare_monsters_t1: {
    id: "expedition_rare_monsters_t1",
    name: "#% increased number of Rare Expedition Monsters in Map",
    statPattern:
      /(\d+)% increased number of Rare Expedition Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_2694800111",
    tier: 1,
    weight: 500,
    minValue: 15,
    maxValue: 30,
    isPrefix: true,
    category: "Expedition",
    valueScore: 68,
    regexHint: "rare.*exp|exp.*rare",
  },
  expedition_logbook_t1: {
    id: "expedition_logbook_t1",
    name: "#% increased Quantity of Expedition Logbooks dropped by Runic Monsters in Map",
    statPattern:
      /(\d+)% increased Quantity of Expedition Logbooks dropped by Runic Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_1083387327",
    tier: 1,
    weight: 250,
    minValue: 20,
    maxValue: 40,
    isPrefix: false,
    category: "Expedition",
    valueScore: 100,
    regexHint: "logb",
  },
  expedition_logbook_t2: {
    id: "expedition_logbook_t2",
    name: "#% increased Quantity of Expedition Logbooks dropped by Runic Monsters in Map",
    statPattern:
      /(\d+)% increased Quantity of Expedition Logbooks dropped by Runic Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_1083387327",
    tier: 2,
    weight: 550,
    minValue: 10,
    maxValue: 19,
    isPrefix: false,
    category: "Expedition",
    valueScore: 65,
    regexHint: "logb",
  },
  expedition_artifacts_t1: {
    id: "expedition_artifacts_t1",
    name: "#% increased quantity of Expedition Artifacts dropped by Monsters in Map",
    statPattern:
      /(\d+)% increased quantity of (?:Expedition )?Artifacts dropped by Monsters(?: in Map)?/i,
    tradeStatId: "explicit.stat_4219583418",
    tier: 1,
    weight: 500,
    minValue: 15,
    maxValue: 30,
    isPrefix: false,
    category: "Expedition",
    valueScore: 60,
    regexHint: "arti",
  },

  // Boss / Overseer
  boss_item_rarity_t1: {
    id: "boss_item_rarity_t1",
    name: "#% increased Rarity of Items dropped by Map Bosses",
    statPattern:
      /(\d+)% increased Rarity of Items dropped by Map Bosses/i,
    tradeStatId: "explicit.stat_4255069232",
    tier: 1,
    weight: 400,
    minValue: 20,
    maxValue: 40,
    isPrefix: true,
    category: "Boss",
    valueScore: 78,
    regexHint: "rar.*boss|boss.*rar",
  },
  boss_waystone_qty_t1: {
    id: "boss_waystone_qty_t1",
    name: "#% increased Quantity of Waystones dropped by Map Bosses",
    statPattern:
      /(\d+)% increased Quantity of Waystones dropped by Map Bosses/i,
    tradeStatId: "explicit.stat_1457896329",
    tier: 1,
    weight: 300,
    minValue: 20,
    maxValue: 40,
    isPrefix: false,
    category: "Boss",
    valueScore: 92,
    regexHint: "ways.*boss|boss.*ways",
  },
  boss_waystone_qty_t2: {
    id: "boss_waystone_qty_t2",
    name: "#% increased Quantity of Waystones dropped by Map Bosses",
    statPattern:
      /(\d+)% increased Quantity of Waystones dropped by Map Bosses/i,
    tradeStatId: "explicit.stat_1457896329",
    tier: 2,
    weight: 650,
    minValue: 10,
    maxValue: 19,
    isPrefix: false,
    category: "Boss",
    valueScore: 55,
    regexHint: "ways",
  },

  // Abyss
  abyss_monster_spawn_t1: {
    id: "abyss_monster_spawn_t1",
    name: "Abysses in Map spawn #% increased Monsters",
    statPattern: /Abysses(?: in Map)? spawn (\d+)% increased Monsters/i,
    tradeStatId: "explicit.stat_944630113",
    tier: 1,
    weight: 400,
    minValue: 20,
    maxValue: 40,
    isPrefix: true,
    category: "Abyss",
    valueScore: 82,
    regexHint: "spawn",
  },
  abyss_monster_spawn_t2: {
    id: "abyss_monster_spawn_t2",
    name: "Abysses in Map spawn #% increased Monsters",
    statPattern: /Abysses(?: in Map)? spawn (\d+)% increased Monsters/i,
    tradeStatId: "explicit.stat_944630113",
    tier: 2,
    weight: 750,
    minValue: 10,
    maxValue: 19,
    isPrefix: true,
    category: "Abyss",
    valueScore: 48,
    regexHint: "spawn",
  },
  abyss_desecrated_t1: {
    id: "abyss_desecrated_t1",
    name: "#% increased chance for Desecrated Currency from Abysses in Map",
    statPattern:
      /(\d+)% increased chance (?:for Desecrated Currency from Abysses(?: in Map)?|to find Desecrated Currency)/i,
    tradeStatId: "explicit.stat_1710200734",
    tier: 1,
    weight: 350,
    minValue: 15,
    maxValue: 30,
    isPrefix: false,
    category: "Abyss",
    valueScore: 90,
    regexHint: "dese",
  },
  abyss_depths_t1: {
    id: "abyss_depths_t1",
    name: "Abysses in Map have #% increased chance to lead to an Abyssal Depths",
    statPattern:
      /Abysses(?: in Map)? have (\d+)% increased chance to lead to an Abyssal Depths/i,
    tradeStatId: "explicit.stat_2722831300",
    tier: 1,
    weight: 450,
    minValue: 20,
    maxValue: 40,
    isPrefix: false,
    category: "Abyss",
    valueScore: 75,
    regexHint: "depth",
  },
  abyss_extra_t1: {
    id: "abyss_extra_t1",
    name: "Map contains # additional Abysses",
    statPattern: /Map contains (\d+) additional Abysses/i,
    tradeStatId: "explicit.stat_3490187949",
    tier: 1,
    weight: 900,
    minValue: 1,
    maxValue: 1,
    isPrefix: false,
    category: "Abyss",
    valueScore: 35,
    regexHint: "abyss",
  },
  abyss_pit_reward_t1: {
    id: "abyss_pit_reward_t1",
    name: "Abyss Pits in Map are twice as likely to have Rewards",
    statPattern: /Abyss Pits(?: in Map)? are twice as likely to have Rewards/i,
    tradeStatId: "explicit.stat_4256531808",
    tier: 1,
    weight: 1000,
    minValue: 1,
    maxValue: 1,
    isPrefix: false,
    category: "Abyss",
    valueScore: 30,
    regexHint: "pit",
  },
  abyss_rare_spawn_t1: {
    id: "abyss_rare_spawn_t1",
    name: "# additional Rare Monsters are spawned from Abysses in Map",
    statPattern:
      /(\d+) additional Rare Monsters are spawned from Abysses(?: in Map)?/i,
    tradeStatId: "explicit.stat_243380454",
    tier: 1,
    weight: 950,
    minValue: 1,
    maxValue: 2,
    isPrefix: false,
    category: "Abyss",
    valueScore: 32,
    regexHint: "rare.*aby",
  },

  // Breach fillers
  breach_wombgift_qty_t1: {
    id: "breach_wombgift_qty_t1",
    name: "#% increased Quantity of Wombgifts found in Map",
    statPattern: /(\d+)% increased Quantity of Wombgifts found(?: in Map)?/i,
    tradeStatId: "explicit.stat_472809816",
    tier: 1,
    weight: 1000,
    minValue: 30,
    maxValue: 60,
    isPrefix: false,
    category: "Breach",
    valueScore: 28,
    regexHint: "womb",
  },
  breach_unstable_rare_t1: {
    id: "breach_unstable_rare_t1",
    name: "Unstable Breaches in Map spawn # additional Rare Monsters when Stabilised",
    statPattern:
      /Unstable Breaches(?: in Map)? spawn (\d+) additional Rare Monsters when Stabilised/i,
    tradeStatId: "explicit.stat_3762913035",
    tier: 1,
    weight: 1100,
    minValue: 1,
    maxValue: 3,
    isPrefix: false,
    category: "Breach",
    valueScore: 80,
    regexHint: "unstab",
  },
  breach_vruun_chance_t1: {
    id: "breach_vruun_chance_t1",
    name: "Unstable Breaches in Map have #% increased chance to contain Vruun, Marshal of Xesht",
    statPattern:
      /Unstable Breaches(?: in Map)? have (\d+)% increased chance to contain Vruun/i,
    tradeStatId: "explicit.stat_2433436306",
    tier: 1,
    weight: 1200,
    minValue: 20,
    maxValue: 50,
    isPrefix: false,
    category: "Breach",
    valueScore: 22,
    regexHint: "vruun",
  },

  // Delirium fillers
  delirium_fog_duration_t1: {
    id: "delirium_fog_duration_t1",
    name: "Delirium Fog in Map lasts # additional seconds before dissipating",
    statPattern:
      /Delirium Fog(?: in Map)? lasts (\d+) additional seconds before dissipating/i,
    tradeStatId: "explicit.stat_1174954559",
    tier: 1,
    weight: 1100,
    minValue: 6,
    maxValue: 12,
    isPrefix: false,
    category: "Delirium",
    valueScore: 28,
    regexHint: "fog",
  },
  delirium_mirror_shards_t1: {
    id: "delirium_mirror_shards_t1",
    name: "Delirium Fog in Map spawns #% increased MirrorShards",
    statPattern:
      /Delirium Fog(?: in Map)? spawns (\d+)% increased MirrorShards/i,
    tradeStatId: "explicit.stat_900933517",
    tier: 1,
    weight: 1050,
    minValue: 12,
    maxValue: 26,
    isPrefix: false,
    category: "Delirium",
    valueScore: 30,
    regexHint: "shard",
  },
  delirium_timer_pause_t1: {
    id: "delirium_timer_pause_t1",
    name: "Slaying Rare Monsters in Map pauses the Delirium Mirror Timer for # seconds",
    statPattern:
      /Slaying Rare Monsters(?: in Map)? pauses the Delirium Mirror Timer for (\d+) seconds/i,
    tradeStatId: "explicit.stat_2323782229",
    tier: 1,
    weight: 1150,
    minValue: 3,
    maxValue: 5,
    isPrefix: false,
    category: "Delirium",
    valueScore: 26,
    regexHint: "pause",
  },

  // Expedition fillers
  expedition_markers_t1: {
    id: "expedition_markers_t1",
    name: "Map contains #% increased number of Runic Monster Markers",
    statPattern:
      /Map contains (\d+)% increased number of Runic Monster Markers/i,
    tradeStatId: "explicit.stat_1640965354",
    tier: 1,
    weight: 1000,
    minValue: 15,
    maxValue: 30,
    isPrefix: true,
    category: "Expedition",
    valueScore: 30,
    regexHint: "runic",
  },
  expedition_explosive_radius_t1: {
    id: "expedition_explosive_radius_t1",
    name: "#% increased Expedition Explosive Radius in Map",
    statPattern:
      /(\d+)% increased Expedition Explosive Radius(?: in Map)?/i,
    tradeStatId: "explicit.stat_3289828378",
    tier: 1,
    weight: 1100,
    minValue: 15,
    maxValue: 30,
    isPrefix: false,
    category: "Expedition",
    valueScore: 28,
    regexHint: "explo",
  },
  expedition_remnants_t1: {
    id: "expedition_remnants_t1",
    name: "Expeditions in Map have +# Remnants",
    statPattern: /Expeditions(?: in Map)? have \+(\d+) Remnants/i,
    tradeStatId: "explicit.stat_3753446846",
    tier: 1,
    weight: 1050,
    minValue: 1,
    maxValue: 2,
    isPrefix: false,
    category: "Expedition",
    valueScore: 32,
    regexHint: "remn",
  },

  // Ritual fillers
  ritual_tribute_t1: {
    id: "ritual_tribute_t1",
    name: "Monsters Sacrificed at Ritual Altars in Map grant #% increased Tribute",
    statPattern:
      /Monsters Sacrificed at Ritual Altars(?: in Map)? grant (\d+)% increased Tribute/i,
    tradeStatId: "explicit.stat_159726667",
    tier: 1,
    weight: 1000,
    minValue: 18,
    maxValue: 30,
    isPrefix: false,
    category: "Ritual",
    valueScore: 35,
    regexHint: "trib",
  },
  ritual_reroll_t1: {
    id: "ritual_reroll_t1",
    name: "Ritual Altars in Map allow rerolling Favours # additional times",
    statPattern:
      /Ritual Altars(?: in Map)? allow rerolling Favours (\d+) additional times/i,
    tradeStatId: "explicit.stat_120737942",
    tier: 1,
    weight: 950,
    minValue: 1,
    maxValue: 3,
    isPrefix: false,
    category: "Ritual",
    valueScore: 40,
    regexHint: "reroll",
  },
  ritual_omen_t1: {
    id: "ritual_omen_t1",
    name: "Ritual Favours in Map have #% increased chance to be Omens",
    statPattern:
      /Ritual Favours(?: in Map)? have (\d+)% increased chance to be Omens/i,
    tradeStatId: "explicit.stat_4219853180",
    tier: 1,
    weight: 900,
    minValue: 35,
    maxValue: 70,
    isPrefix: false,
    category: "Ritual",
    valueScore: 42,
    regexHint: "omen",
  },
  ritual_defer_t1: {
    id: "ritual_defer_t1",
    name: "Favours Deferred at Ritual Altars in Map reappear #% sooner",
    statPattern:
      /Favours Deferred at Ritual Altars(?: in Map)? reappear (\d+)% sooner/i,
    tradeStatId: "explicit.stat_28208665",
    tier: 1,
    weight: 1100,
    minValue: 25,
    maxValue: 40,
    isPrefix: false,
    category: "Ritual",
    valueScore: 25,
    regexHint: "defer",
  },

  // Boss fillers
  boss_xp_t1: {
    id: "boss_xp_t1",
    name: "Map Bosses grant #% increased Experience",
    statPattern: /Map Bosses grant (\d+)% increased Experience/i,
    tradeStatId: "explicit.stat_3860150265",
    tier: 1,
    weight: 1100,
    minValue: 40,
    maxValue: 80,
    isPrefix: false,
    category: "Boss",
    valueScore: 28,
    regexHint: "boss.*xp|xp.*boss",
  },
  boss_item_qty_t1: {
    id: "boss_item_qty_t1",
    name: "#% increased Quantity of Items dropped by Map Bosses",
    statPattern:
      /(\d+)% increased Quantity of Items dropped by Map Bosses/i,
    tradeStatId: "explicit.stat_3119172063",
    tier: 1,
    weight: 1000,
    minValue: 13,
    maxValue: 20,
    isPrefix: false,
    category: "Boss",
    valueScore: 38,
    regexHint: "boss.*quan",
  },

  // Temple / Vaal fillers
  temple_beacon_pack_t1: {
    id: "temple_beacon_pack_t1",
    name: "#% increased Pack Size for Monsters around Vaal Beacons in Map",
    statPattern:
      /(\d+)% increased Pack Size for Monsters around Vaal Beacons(?: in Map)?/i,
    tradeStatId: "explicit.stat_890040946",
    tier: 1,
    weight: 1100,
    minValue: 10,
    maxValue: 30,
    isPrefix: false,
    category: "Temple",
    valueScore: 28,
    regexHint: "vaal",
  },
  temple_crystal_t1: {
    id: "temple_crystal_t1",
    name: "#% chance to gain an additional Crystal from Vaal Beacons in Map",
    statPattern:
      /(\d+)% chance to gain an additional Crystal from Vaal Beacons(?: in Map)?/i,
    tradeStatId: "explicit.stat_1940774881",
    tier: 1,
    weight: 1050,
    minValue: 5,
    maxValue: 10,
    isPrefix: false,
    category: "Temple",
    valueScore: 32,
    regexHint: "cryst",
  },
  temple_chest_rare_t1: {
    id: "temple_chest_rare_t1",
    name: "#% increased chance Vaal Beacon Chests are Rare in Map",
    statPattern:
      /(\d+)% increased chance Vaal Beacon Chests are Rare(?: in Map)?/i,
    tradeStatId: "explicit.stat_2514439422",
    tier: 1,
    weight: 1150,
    minValue: 30,
    maxValue: 60,
    isPrefix: false,
    category: "Temple",
    valueScore: 26,
    regexHint: "chest",
  },

  // Shared generic junk (0.3.1 pool flood) — high weight, low score
  junk_item_rarity_t1: {
    id: "junk_item_rarity_t1",
    name: "#% increased Rarity of Items found in Map",
    statPattern: /(\d+)% increased Rarity of Items found in Map/i,
    tradeStatId: "explicit.stat_4011150624",
    tier: 1,
    weight: 1400,
    minValue: 8,
    maxValue: 12,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 18,
    regexHint: "rar",
  },
  junk_gold_t1: {
    id: "junk_gold_t1",
    name: "#% increased Gold found in Map",
    statPattern: /(\d+)% increased Gold found in Map/i,
    tradeStatId: "explicit.stat_1276056105",
    tier: 1,
    weight: 1500,
    minValue: 25,
    maxValue: 35,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "gold",
  },
  junk_xp_t1: {
    id: "junk_xp_t1",
    name: "#% increased Experience gain in Map",
    statPattern: /(\d+)% increased Experience gain in Map/i,
    tradeStatId: "explicit.stat_57434274",
    tier: 1,
    weight: 1450,
    minValue: 12,
    maxValue: 18,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 14,
    regexHint: "exp",
  },
  junk_magic_mons_t1: {
    id: "junk_magic_mons_t1",
    name: "Map has #% increased Magic Monsters",
    statPattern: /Map has (\d+)% increased Magic Monsters/i,
    tradeStatId: "explicit.stat_3873704640",
    tier: 1,
    weight: 1400,
    minValue: 30,
    maxValue: 40,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 16,
    regexHint: "magic",
  },
  junk_rare_mons_t1: {
    id: "junk_rare_mons_t1",
    name: "Map has #% increased number of Rare Monsters",
    statPattern: /Map has (\d+)% increased number of Rare Monsters/i,
    tradeStatId: "explicit.stat_3793155082",
    tier: 1,
    weight: 1350,
    minValue: 25,
    maxValue: 35,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 20,
    regexHint: "rare",
  },
  junk_rare_chests_t1: {
    id: "junk_rare_chests_t1",
    name: "Map contains # additional Rare Chests",
    statPattern: /Map contains (\d+) additional Rare Chests/i,
    tradeStatId: "explicit.stat_231864447",
    tier: 1,
    weight: 1300,
    minValue: 2,
    maxValue: 3,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 18,
    regexHint: "chest",
  },
  junk_monster_eff_t1: {
    id: "junk_monster_eff_t1",
    name: "Monsters have #% increased Effectiveness",
    statPattern: /Monsters have (\d+)% increased Effectiveness/i,
    tradeStatId: "explicit.stat_2065500219",
    tier: 1,
    weight: 1250,
    minValue: 10,
    maxValue: 15,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 22,
    regexHint: "effe",
  },
  junk_extra_essence_t1: {
    id: "junk_extra_essence_t1",
    name: "Map contains an additional Essence",
    statPattern: /Map contains (?:an )?additional Essence/i,
    tradeStatId: "explicit.stat_2162684861",
    tier: 1,
    weight: 1300,
    minValue: 1,
    maxValue: 1,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 15,
    regexHint: "essence",
  },
  junk_extra_exile_t1: {
    id: "junk_extra_exile_t1",
    name: "Area is inhabited by 1 additional Rogue Exile",
    statPattern: /(?:Area|Map) is inhabited by (\d+) additional Rogue Exile/i,
    tradeStatId: "explicit.stat_3550168289",
    tier: 1,
    weight: 1300,
    minValue: 1,
    maxValue: 1,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 15,
    regexHint: "exile",
  },
  junk_extra_azmeri_t1: {
    id: "junk_extra_azmeri_t1",
    name: "Area contains 1 additional Azmeri Spirit",
    statPattern: /(?:Area|Map) contains (\d+) additional Azmeri Spirit/i,
    tradeStatId: "explicit.stat_358129101",
    tier: 1,
    weight: 1300,
    minValue: 1,
    maxValue: 1,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 15,
    regexHint: "azmer",
  },
  junk_extra_summon_t1: {
    id: "junk_extra_summon_t1",
    name: "Map contains 1 additional Summoning Circles",
    statPattern: /Map contains (\d+) additional Summoning Circles?/i,
    tradeStatId: "explicit.stat_2839545956",
    tier: 1,
    weight: 1300,
    minValue: 1,
    maxValue: 1,
    isPrefix: true,
    category: "Irradiated",
    valueScore: 15,
    regexHint: "summon",
  },
  junk_extra_shrine_t1: {
    id: "junk_extra_shrine_t1",
    name: "Map contains # additional Shrines",
    statPattern: /Map contains (\d+) additional Shrines?/i,
    tradeStatId: "explicit.stat_1468737867",
    tier: 1,
    weight: 1400,
    minValue: 1,
    maxValue: 2,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 14,
    regexHint: "shrine",
  },
  junk_extra_strongbox_t1: {
    id: "junk_extra_strongbox_t1",
    name: "Map contains # additional Strongboxes",
    statPattern: /Map contains (\d+) additional Strongboxes?/i,
    tradeStatId: "explicit.stat_3240183538",
    tier: 1,
    weight: 1400,
    minValue: 1,
    maxValue: 2,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 14,
    regexHint: "strong",
  },
  junk_shrine_chance_t1: {
    id: "junk_shrine_chance_t1",
    name: "Map has #% increased chance to contain Shrines",
    statPattern: /Map has (\d+)% increased chance to contain Shrines/i,
    tradeStatId: "explicit.stat_689816330",
    tier: 1,
    weight: 1450,
    minValue: 70,
    maxValue: 100,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "shrine",
  },
  junk_strongbox_chance_t1: {
    id: "junk_strongbox_chance_t1",
    name: "Map has #% increased chance to contain Strongboxes",
    statPattern: /Map has (\d+)% increased chance to contain Strongboxes/i,
    tradeStatId: "explicit.stat_4279535856",
    tier: 1,
    weight: 1450,
    minValue: 70,
    maxValue: 100,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "strong",
  },
  junk_essence_chance_t1: {
    id: "junk_essence_chance_t1",
    name: "Map has #% increased chance to contain Essences",
    statPattern: /Map has (\d+)% increased chance to contain Essences/i,
    tradeStatId: "explicit.stat_1825943485",
    tier: 1,
    weight: 1450,
    minValue: 70,
    maxValue: 100,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "essence",
  },
  junk_exile_chance_t1: {
    id: "junk_exile_chance_t1",
    name: "Map has #% increased chance to contain Rogue Exiles",
    statPattern: /Map has (\d+)% increased chance to contain Rogue Exiles/i,
    tradeStatId: "explicit.stat_1352729973",
    tier: 1,
    weight: 1450,
    minValue: 70,
    maxValue: 100,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "exile",
  },
  junk_summon_chance_t1: {
    id: "junk_summon_chance_t1",
    name: "Map has #% increased chance to contain a Summoning Circle",
    statPattern:
      /Map has (\d+)% increased chance to contain a Summoning Circle/i,
    tradeStatId: "explicit.stat_267210597",
    tier: 1,
    weight: 1450,
    minValue: 70,
    maxValue: 100,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "summon",
  },
  junk_azmeri_chance_t1: {
    id: "junk_azmeri_chance_t1",
    name: "Map has #% increased chance to contain Azmeri Spirits",
    statPattern: /Map has (\d+)% increased chance to contain Azmeri Spirits/i,
    tradeStatId: "explicit.stat_3815617979",
    tier: 1,
    weight: 1450,
    minValue: 70,
    maxValue: 100,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 12,
    regexHint: "azmer",
  },
  junk_map_mods_t1: {
    id: "junk_map_mods_t1",
    name: "Map has # additional random Modifiers",
    statPattern: /Map has (\d+) additional random Modifiers/i,
    tradeStatId: "explicit.stat_588512487",
    tier: 1,
    weight: 1200,
    minValue: 1,
    maxValue: 2,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 20,
    regexHint: "mod",
  },
  junk_rare_extra_mod_t1: {
    id: "junk_rare_extra_mod_t1",
    name: "Rare Monsters in Map have a #% Surpassing chance to have an additional Modifier",
    statPattern:
      /Rare Monsters(?: in Map)? have a (\d+)% Surpassing chance to have an additional Modifier/i,
    tradeStatId: "explicit.stat_3732878551",
    tier: 1,
    weight: 1250,
    minValue: 50,
    maxValue: 80,
    isPrefix: false,
    category: "Irradiated",
    valueScore: 18,
    regexHint: "surpass",
  },
};

export function findTabletBaseByName(name: string): TabletBaseDefinition | null {
  const normalized = name.trim().toLowerCase();
  for (const base of Object.values(TABLET_BASES)) {
    if (base.name.toLowerCase() === normalized) return base;
    if (base.aliases.some((a) => a.toLowerCase() === normalized)) return base;
    if (normalized.includes(base.name.toLowerCase())) return base;
    if (base.aliases.some((a) => normalized.includes(a.toLowerCase()))) {
      return base;
    }
  }
  return null;
}

export function getHighValueModsForBase(
  baseId: string,
  minScore = 70,
): TabletModDefinition[] {
  const base = TABLET_BASES[baseId];
  if (!base) return [];
  const ids = [...base.allowedPrefixPool, ...base.allowedSuffixPool];
  return ids
    .map((id) => TABLET_MOD_WEIGHTS[id])
    .filter((m): m is TabletModDefinition => !!m && m.valueScore >= minScore)
    .sort((a, b) => b.valueScore - a.valueScore);
}